[programs.localnet]
drift_client = "23gFaqsYmR1zrQVYiyWJ5xnEFqmuKLYoGasgewDTHD1u"

[[test.genesis]]
address = "AsW7LnXB9UA1uec9wi9MctYTgTz7YH9snhxd16GsFaGX"
program = "./deps/protocol-v1/target/deploy/clearing_house.so"

[provider]
cluster = "localnet"
wallet = "/Users/crisp/.config/solana/id.json"

[scripts]
test = "ts-mocha -t 1000000 tests/drift-client.ts"
